import React from "react";
import logo from "../images/logo.jpg";

const InfoPage = () => {
  return (
    <div className="min-h-screen flex flex-col p-10 bg-[#27293D] text-white">
      {/* Logo Section */}
      <div className="flex justify-center mb-4">
        <img src={logo} alt="Money Stretch Logo" className="h-70 w-70 rounded-full" />
      </div>
      {/* Title Section */}
      <header className="text-center mb-8">
        <h1 className="text-5xl font-extrabold text-yellow-400">Balance Sheet 101</h1>
      </header>
      
      <div className="space-y-6">
        <section className="bg-[#31344A] p-6 rounded-lg shadow-lg mt-8">
          <h2 className="text-2xl font-bold text-yellow-300">Assets</h2>
          <ul className="mt-2 text-lg list-disc pl-6">
            <li><strong>Current assets</strong> - Assets that are expected to be converted into cash or used up within one year, such as cash, accounts receivable, inventory, and prepaid expenses.</li>
            <li><strong>Non-current assets</strong> - Long-term assets that a company uses for operations and are not expected to be converted into cash within a year, including property, plant, equipment, and intangible assets like patents.</li>
          </ul>
        </section>

        <section className="bg-[#31344A] p-6 rounded-lg shadow-lg mt-8">
          <h2 className="text-2xl font-bold text-yellow-300">Liabilities</h2>
          <ul className="mt-2 text-lg list-disc pl-6">
            <li><strong>Current liabilities</strong> - Short-term financial obligations that a company must settle within a year, such as accounts payable, short-term debt, and accrued expenses.</li>
            <li><strong>Non-current liabilities</strong> - Long-term financial obligations that are due beyond one year, including long-term debt, deferred tax liabilities, and pension obligations.</li>
          </ul>
        </section>

        <section className="bg-[#31344A] p-6 rounded-lg shadow-lg mt-8">
          <h2 className="text-2xl font-bold text-yellow-300">Shareholders' Equity</h2>
          <ul className="mt-2 text-lg list-disc pl-6">
            <li><strong>Common stock</strong> - The basic ownership unit in a company, representing shares that investors purchase to gain equity ownership.</li>
            <li><strong>Retained earnings</strong> - The portion of a company's net income that is reinvested in the business rather than distributed as dividends to shareholders.</li>
            <li><strong>Equity</strong> - The residual interest in the assets of a company after deducting liabilities, representing the ownership stake held by investors.</li>
          </ul>
        </section>

        <section className="bg-[#31344A] p-6 rounded-lg shadow-lg mt-8">
          <h2 className="text-2xl font-bold text-yellow-300">Basic Accounting Terms</h2>
          <ul className="mt-2 text-lg list-disc pl-6">
            <li><strong>Revenue</strong> - The total income generated by a business from sales of goods or services.</li>
            <li><strong>Expenses</strong> - The costs incurred by a business in order to generate revenue.</li>
            <li><strong>Net Income</strong> - The profit remaining after all expenses, taxes, and costs have been deducted from revenue.</li>
            <li><strong>Gross Profit</strong> - Revenue minus the cost of goods sold (COGS), representing the profit before operating expenses.</li>
            <li><strong>Accounts Payable</strong> - The amount a company owes to suppliers or creditors for goods and services received.</li>
            <li><strong>Accounts Receivable</strong> - The amount owed to a company by customers who have purchased goods or services on credit.</li>
            <li><strong>Depreciation</strong> - The gradual reduction in value of a tangible asset over time due to wear and tear.</li>
            <li><strong>Liquidity</strong> - The ability of a business to meet its short-term financial obligations.</li>
          </ul>
        </section>
      </div>
    </div>
  );
};

export default InfoPage;
